"$schema" = 'https://starship.rs/config-schema.json'

format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$fill\
$package\
$c\
$cmake\
$java\
$gradle\
$lua\
$nodejs\
$python\
$rust\
$zig\
$container $status $cmd_duration $jobs\
$line_break\
$character"""


[fill]
symbol = " "

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true


[username]
style_user = "#68D2E8"
show_always = true

[python]
format = "$symbol$version "
style = "bold green"

[rust]
format = "$symbol$version "
style = "bold green"

[zig]
format = "$symbol$version "
style = "bold green"

[nodejs]
format = "$symbol$version "
style = "bold green"

[lua]
format = "$symbol$version "
style = "bold green"

[c]
format = "$symbol$version "
style = "bold green"

[java]
format = "$symbol$version "
style = "bold green"

[cmake]
format = "$symbol$version "
style = "bold green"

[gradle]
format = "$symbol$version "
style = "bold green"
